repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.1.0
    hooks:
      - id: setup-cfg-fmt
  - repo: https://github.com/PyCQA/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        additional_dependencies: [flake8-typing-imports]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.982"
    hooks:
      - id: mypy
