[build-system]
requires = [
  "setuptools >= 42",
  "wheel",
  "setuptools_scm[toml]>=3.4"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/napari_omero/_version.py"

[tool.black]
target-version = ['py36', 'py37']
skip-string-normalization = true
line-length = 79
